VAN-4420 Allow to override the sonar scanner version in Sonar scanner module
ollionorg/codepipes-ci-cd-modules pull request #220
Opened 2024-01-04 13:59 UTC by akashcldcvr

2024-01-04 14:07 UTC, NikhilVerma approved these changes

2024-01-04 14:13 UTC, dshelley66 requested changes
@akashcldcvr The reason we were storing our own version of this container on GCR is because builds were getting rate limited on DH. If you look in scripts/container-load/container-manifest.yaml, you can add a new version of this container in there so that it is available on DH. 
I think keeping your sonar_scanner_version makes sense but switching back to the DH to pull it will be problematic (i.e. leave us-docker.pkg.dev/codepipes-stating...

There is a README.md in the container-load directory which explains how this works - let me know if you need help

2024-01-04 14:13 UTC, shwetanshu-cldcvr submitted a review, later dismissed
LGTM

2024-01-09 12:38 UTC, shwetanshu-cldcvr approved these changes
LGTM

2024-01-09 12:42 UTC, dshelley66 approved these changes

2024-01-09 12:42 UTC, merged